/**
 * KV Storage wrapper for activation records
 *
 * KV Schema:
 *   Key: "key:{UPPERCASED_KEY}"  => ActivationRecord
 *   Key: "machine:{MACHINE_ID}"   => string[] (list of keys bound to this machine)
 *   Key: "stats:keys_generated"   => number (total keys generated counter)
 */

export interface DeviceInfo {
  machineId: string
  activatedAt: string
  label: string
}

export interface ActivationRecord {
  key: string
  tier: 'pro' | 'premium'
  plan?: string        // subscription plan id or 'pro'
  code?: string        // key code: PRO | PR1 | PR2 | PR3 | PR4
  maxDevices: number
  devices: DeviceInfo[]
  createdAt: string
  expiresAt: string | null
  purchaseOrderId?: string
  revoked: boolean
}

export class ActivationStore {
  private kv: KVNamespace

  constructor(kv: KVNamespace) {
    this.kv = kv
  }

  /** Store a newly generated key (before it's been activated) */
  async storeGeneratedKey(record: ActivationRecord): Promise<void> {
    await this.kv.put(`key:${record.key}`, JSON.stringify(record))
    // Increment counter
    const current = await this.kv.get('stats:keys_generated')
    const count = (current ? parseInt(current, 10) : 0) + 1
    await this.kv.put('stats:keys_generated', count.toString())
  }

  /** Get an activation record by key */
  async getByKey(key: string): Promise<ActivationRecord | null> {
    const raw = await this.kv.get(`key:${key.toUpperCase()}`)
    if (!raw) return null
    return JSON.parse(raw) as ActivationRecord
  }

  /** Save/update an activation record */
  async save(record: ActivationRecord): Promise<void> {
    await this.kv.put(`key:${record.key}`, JSON.stringify(record))
  }

  /** Get all keys bound to a machine */
  async getKeysByMachine(machineId: string): Promise<string[]> {
    const raw = await this.kv.get(`machine:${machineId}`)
    if (!raw) return []
    return JSON.parse(raw) as string[]
  }

  /** Register a machine binding */
  async addMachineBinding(machineId: string, key: string): Promise<void> {
    const current = await this.getKeysByMachine(machineId)
    if (!current.includes(key.toUpperCase())) {
      current.push(key.toUpperCase())
      await this.kv.put(`machine:${machineId}`, JSON.stringify(current))
    }
  }

  /** Remove a machine binding */
  async removeMachineBinding(machineId: string, key: string): Promise<void> {
    const current = await this.getKeysByMachine(machineId)
    const filtered = current.filter((k) => k !== key.toUpperCase())
    if (filtered.length > 0) {
      await this.kv.put(`machine:${machineId}`, JSON.stringify(filtered))
    } else {
      await this.kv.delete(`machine:${machineId}`)
    }
  }

  /** Check if a key has been generated by the server */
  async keyExists(key: string): Promise<boolean> {
    return (await this.kv.get(`key:${key.toUpperCase()}`)) !== null
  }

  /** Get total keys generated */
  async getTotalKeysGenerated(): Promise<number> {
    const raw = await this.kv.get('stats:keys_generated')
    return raw ? parseInt(raw, 10) : 0
  }
}
