/**
 * ASRData - 语音识别结果数据结构
 * 从 AsrTools Python 版本移植到 TypeScript
 */

import * as fs from 'fs'
import * as path from 'path'

export class ASRDataSeg {
  text: string
  startTime: number
  endTime: number

  constructor(text: string, startTime: number, endTime: number) {
    this.text = text
    this.startTime = startTime
    this.endTime = endTime
  }

  /** 转换为 SRT 时间戳格式 */
  toSrtTs(): string {
    return `${ASRDataSeg.msToSrtTime(this.startTime)} --> ${ASRDataSeg.msToSrtTime(this.endTime)}`
  }

  /** 转换为 LRC 时间戳格式 */
  toLrcTs(): string {
    const seconds = this.startTime / 1000
    const minutes = Math.floor(seconds / 60)
    const secs = (seconds % 60).toFixed(2)
    return `[${String(minutes).padStart(2, '0')}:${secs}]`
  }

  /** 转换为 ASS 时间戳格式，返回 [start, end] */
  toAssTs(): [string, string] {
    return [ASRDataSeg.msToAssTs(this.startTime), ASRDataSeg.msToAssTs(this.endTime)]
  }

  get transcript(): string {
    return this.text
  }

  /** 毫秒 → SRT 时间格式 (HH:MM:SS,mmm) */
  static msToSrtTime(ms: number): string {
    const totalSeconds = Math.floor(ms / 1000)
    const milliseconds = ms % 1000
    const minutes = Math.floor(totalSeconds / 60)
    const seconds = totalSeconds % 60
    const hours = Math.floor(minutes / 60)
    const mins = minutes % 60
    return `${String(hours).padStart(2, '0')}:${String(mins).padStart(2, '0')}:${String(seconds).padStart(2, '0')},${String(milliseconds).padStart(3, '0')}`
  }

  /** 毫秒 → ASS 时间格式 (H:MM:SS.cc) */
  static msToAssTs(ms: number): string {
    const totalSeconds = Math.floor(ms / 1000)
    const milliseconds = ms % 1000
    const minutes = Math.floor(totalSeconds / 60)
    const seconds = totalSeconds % 60
    const hours = Math.floor(minutes / 60)
    const mins = minutes % 60
    const centiseconds = Math.floor(milliseconds / 10)
    return `${hours}:${String(mins).padStart(2, '0')}:${String(seconds).padStart(2, '0')}.${String(centiseconds).padStart(2, '0')}`
  }
}

export class ASRData {
  segments: ASRDataSeg[]

  constructor(segments: ASRDataSeg[]) {
    this.segments = segments
  }

  hasData(): boolean {
    return this.segments.length > 0
  }

  /** 转换为纯文本（无时间戳） */
  toTxt(): string {
    return this.segments.map(seg => seg.transcript).join('\n')
  }

  /** 转换为 SRT 格式 */
  toSrt(): string {
    return this.segments
      .map((seg, n) => `${n + 1}\n${seg.toSrtTs()}\n${seg.transcript}\n`)
      .join('\n')
  }

  /** 转换为 LRC 格式 */
  toLrc(): string {
    return this.segments
      .map(seg => `${seg.toLrcTs()}${seg.transcript}`)
      .join('\n')
  }

  /** 转换为 ASS 格式 */
  toAss(styleStr?: string, layout: string = '原文在上'): string {
    if (!styleStr) {
      styleStr = `[V4+ Styles]
Format: Name,Fontname,Fontsize,PrimaryColour,SecondaryColour,OutlineColour,BackColour,Bold,Italic,Underline,StrikeOut,ScaleX,ScaleY,Spacing,Angle,BorderStyle,Outline,Shadow,Alignment,MarginL,MarginR,MarginV,Encoding
Style: Default,微软雅黑,66,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,2,0,2,10,10,10,1
Style: Translate,微软雅黑,40,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,2,0,2,10,10,10,1`
    }

    let assContent = `[Script Info]
; Script generated by Videobox
ScriptType: v4.00+
PlayResX: 1280
PlayResY: 720

${styleStr}

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`

    const dialogueTemplate = 'Dialogue: 0,{start},{end},{style},,0,0,0,,{text}\n'

    for (const seg of this.segments) {
      const [startTime, endTime] = seg.toAssTs()

      if (seg.text.includes('\n')) {
        const [original, translate] = seg.text.split('\n')
        if (layout === '译文在上' && translate) {
          assContent += dialogueTemplate
            .replace('{start}', startTime).replace('{end}', endTime)
            .replace('{style}', 'Secondary').replace('{text}', original)
          assContent += dialogueTemplate
            .replace('{start}', startTime).replace('{end}', endTime)
            .replace('{style}', 'Default').replace('{text}', translate)
        } else if (layout === '原文在上' && translate) {
          assContent += dialogueTemplate
            .replace('{start}', startTime).replace('{end}', endTime)
            .replace('{style}', 'Secondary').replace('{text}', translate)
          assContent += dialogueTemplate
            .replace('{start}', startTime).replace('{end}', endTime)
            .replace('{style}', 'Default').replace('{text}', original)
        } else if (layout === '仅原文') {
          assContent += dialogueTemplate
            .replace('{start}', startTime).replace('{end}', endTime)
            .replace('{style}', 'Default').replace('{text}', original)
        } else if (layout === '仅译文' && translate) {
          assContent += dialogueTemplate
            .replace('{start}', startTime).replace('{end}', endTime)
            .replace('{style}', 'Default').replace('{text}', translate)
        }
      } else {
        assContent += dialogueTemplate
          .replace('{start}', startTime).replace('{end}', endTime)
          .replace('{style}', 'Default').replace('{text}', seg.text)
      }
    }

    return assContent
  }

  /** 保存到文件（根据扩展名选择格式） */
  save(savePath: string, assStyle?: string, layout?: string): string {

    const dir = path.dirname(savePath)
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true })
    }

    let content: string
    if (savePath.endsWith('.srt')) {
      content = this.toSrt()
    } else if (savePath.endsWith('.txt')) {
      content = this.toTxt()
    } else if (savePath.endsWith('.ass')) {
      content = this.toAss(assStyle, layout)
    } else if (savePath.endsWith('.json')) {
      content = JSON.stringify(this.toJson(), null, 2)
    } else {
      throw new Error(`Unsupported file extension: ${savePath}`)
    }

    fs.writeFileSync(savePath, content, 'utf-8')
    return savePath
  }

  toJson(): Record<string, unknown> {
    const result: Record<string, unknown> = {}
    this.segments.forEach((seg, i) => {
      let originalSubtitle: string
      let translatedSubtitle = ''
      if (seg.text.includes('\n')) {
        [originalSubtitle, translatedSubtitle] = seg.text.split('\n')
      } else {
        originalSubtitle = seg.text
      }
      result[String(i + 1)] = {
        start_time: seg.startTime,
        end_time: seg.endTime,
        original_subtitle: originalSubtitle,
        translated_subtitle: translatedSubtitle
      }
    })
    return result
  }
}
